### ISSUE TITLE
Project-level dependency for pydantic-ome-ngff missing

### ISSUE THREAD

**Issue by kephale** [janelia-cosem/fibsem-tools#37]
`pydantic-ome-ngff` is imported but not declared in the dependencies

https://github.com/janelia-cosem/fibsem-tools/blob/00bdfbbe596754dee86b38066db0ab709f47b125/src/fibsem_tools/io/zarr.py#L20

**Comment by d-v-b** [comment]
that's gross! i will fit it immediately

**Comment by d-v-b** [comment]
This happened as a side-effect of me doing a lot of aimless unfocused changes in a dev branch. It should be fixed in 1.3.0

**Comment by d-v-b** [comment]
fixed in https://github.com/janelia-cosem/fibsem-tools/commit/33c38bcab9d384614e146062ef16c15b44dae306
