### ISSUE TITLE
demo url in readme stale

### ISSUE THREAD

**Issue by tlambert03** [janelia-cosem/fibsem-tools#41]
the uri in the readme example looks to be stale:

s3://janelia-cosem-datasets/jrc_sum159-1/jrc_sum159-1.n5/labels/gt/0003/crop26/labels/all/s0/ 

not sure which one you'd want to update it with, (e.g. s3://janelia-cosem-datasets/jrc_sum159-1/jrc_sum159-1.n5/labels/gt/s0/ worked for me, but is a different scale)

**Comment by d-v-b** [comment]
fixed here: https://github.com/janelia-cosem/fibsem-tools/commit/8e100b659f3814f6c822dfb2ad57e531415b58b9
